"use client"
import Head from "next/head";
import Image from "next/image";
import ReactDOMServer from "react-dom/server";
import { Inter } from "@next/font/google";
import { Button, Table, Typography, Layout } from "antd";
const inter = Inter({ subsets: ["latin"] });
import { Wrapper } from "./app.style";
import ImageTest from "./image.png";
import { render } from "react-dom";

export default function Home() {
    const dataSource = Array.from({ length: 10 }, (_, i) => ({
        key: i,
        name: `user-${i}`,
        age: 32 + i,
        address: `${i}-Downing Street`,
        email: `user${i}@gmail.com`,
        phone: "123456789",
    }));

    const columns = [
        {
            title: "Name",
            dataIndex: "name",
            key: "name",
        },
        {
            title: "Age",
            dataIndex: "age",
            key: "age",
        },
        {
            title: "Address",
            dataIndex: "address",
            key: "address",
        },
        {
            title: "Email",
            dataIndex: "email",
            key: "email",
        },
        {
            title: "Phone",
            dataIndex: "phone",
            key: "pnone",
        },
    ];

    const imageStyle = {
        borderRadius: '50%',
        border: '1px solid #fff',
    }

    const content = () => {
        return (
            <Layout style={{ backgroundColor: 'red' }}>
                <Image
                    src={ImageTest}
                    style={imageStyle}
                    alt="Picture of the author"
                />
                <Typography.Title level={4} className={"title"} style={{ color: 'blue' }}>
                    User list
                </Typography.Title>
                <Typography.Title level={4} className={"title"}>
                    User list
                </Typography.Title>
                <Table
                    dataSource={dataSource}
                    columns={columns}
                    bordered
                    pagination={false}
                />
            </Layout>
        );
    };
    const handlePrint = async () => {
        // @ts-ignore
        const html2pdf = (await import("html2pdf.js/dist/html2pdf.min.js")).default;
        const printContent = ReactDOMServer.renderToString(content());
        html2pdf().set().from(printContent).save();
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                {/* render UI */}
                {content()}
                <div className={"btn__container"}>
                    <Button type="primary" onClick={() => handlePrint()}>
                        Print
                    </Button>
                </div>
            </Wrapper>
        </>
    );
}
